#! /bin/sh

gotip() {
	ip addr list | grep '\<inet\>' | grep -qvE '127.0.0.1|vmnet|docker'
}

timer=60
poll=5

while getopts t:p:h opt; do
	case "$opt" in
		t) timer="$OPTARG" ;;
		p) poll="$OPTARG"  ;;
		h) echo "$0 [-t] [-p] [cmd [arg...]]"; exit 0;;
		*) exit 8;;
	esac
done

shift $((OPTIND-1))

while ! gotip && [ $timer -gt 0 ]; do
	echo "Sleeping for $poll seconds with $timer seconds remaining" >> "/tmp/wait4net.$$.log"
	sleep $poll
	timer=$((timer-poll))
done

gotip || exit 63

if [ -n "$1" ]; then
	"$@"
fi
