#! /bin/sh

gotip() {
	ip addr list | grep '\<inet\>' | grep -vq '127.0.0.1'
}

timer=60
poll=5

while getopts t:p: opt; do
   case "$opt" in
      t) timer="$OPTARG" ;;
      p) poll="$OPTARG" ;;
      *) exit 8;;
   esac
done

shift $((OPTIND-1))

while ! gotip && [ $timer -gt 0 ]; do
	echo "Sleeping for $poll seconds with $timer seconds remaining" >> "/tmp/wait4net.$$.log"
	sleep $poll
	timer=$((timer-poll))
done

if [ -n "$1" ] && gotip; then
	"$@"
fi
